default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ubuntu         
  password: your_password  

development:
  <<: *default
  database: your_development_database_name

test:
  <<: *default
  database: your_test_database_name

production:
  <<: *default
  database: your_production_database_name
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>